name: Daily workflow

on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore src

    - name: Build
      run: dotnet build src --configuration Release --no-restore

    - name: Test
      run: dotnet test src --configuration Release --no-build --verbosity diagnostic /p:CollectCoverage=\"false\" /p:Exclude=\"[*.Tests]*\" /p:SkipAutoProps=\"false\" /p:IncludeTestAssembly=\"false\" -m:1

    - name: Update dependencies
      run: dotnet add src/rgvlee.Core.Common package Microsoft.Extensions.Logging

    - name: Test
      run: dotnet test src --configuration Release --verbosity diagnostic /p:CollectCoverage=\"false\" /p:Exclude=\"[*.Tests]*\" /p:SkipAutoProps=\"false\" /p:IncludeTestAssembly=\"false\" -m:1
